// (AI-2) /ai/*, /agent/proposals, /memory, /wishlist over HTTP: shapes,
// household isolation, the proposal state machine, the SSE frames, the
// owner gate and the per-person rate limit. Synthetic households only.

import { describe, it, expect, beforeAll, vi } from "vitest";
import { randomUUID } from "node:crypto";
import { and, eq } from "drizzle-orm";

const mk = (t: string) => `askr-${t}-${process.pid}-${randomUUID().slice(0, 8)}`;
const A_OWNER = mk("a");
const A_MEMBER = mk("am");
const B_OWNER = mk("b");
const C_OWNER = mk("c"); // the usage / budget household
const RL_OWNER = mk("rl"); // the rate-limit household
const HH: Record<string, { householdId: string; ownerUserId: string; actor?: string }> = {};

vi.mock("../middlewares/requireAuth", () => ({
  requireAuth: (
    req: { headers: Record<string, string | string[] | undefined>; userId?: string; actualUserId?: string; householdId?: string; householdOwnerId?: string },
    _res: unknown,
    next: () => void,
  ) => {
    const who = String(req.headers["x-test-user"] ?? A_OWNER);
    const hh = HH[who]!;
    req.userId = hh.ownerUserId; // a member is remapped to the owner, as in production
    req.actualUserId = hh.actor ?? who;
    req.householdId = hh.householdId;
    req.householdOwnerId = hh.ownerUserId;
    next();
  },
}));

import {
  db,
  agentActionsTable,
  agentMemoryTable,
  agentMessagesTable,
  agentProposalsTable,
  aiBudgetTable,
  aiUsageTable,
  allowancePlansTable,
  avalancheSettingsTable,
  budgetLinesTable,
  recurringItemsTable,
  transactionsTable,
  wishlistItemsTable,
} from "@workspace/db";
import { AiChatResponse } from "@workspace/api-zod";
import aiRouter from "../routes/ai";
import { makeTools } from "../ai/tools";
import { queueFakeChat, resetFake } from "../ai/fake";
import { undoDecision } from "../lib/categorizer/review";
import { upsertAgentMemory } from "../lib/agentMemory";
import { addDaysISO, householdToday } from "@workspace/avalanche-core";
import { createTestApp } from "./_helpers/createTestApp";
import { createTestHousehold } from "./_helpers/testHousehold";
import { newRun, seedAskHousehold, type AskHousehold } from "./_helpers/askFixtures";
import { daysAgo } from "./_helpers/aiCategorize";
import { pinEnv } from "./_helpers/aiEnv";

pinEnv({ AI_PROVIDER: "fake", AI_ENABLED: "true", AI_PAUSED: undefined, AI_SSE_PING_MS: "40", AI_MODEL_CHAT: undefined });

const { baseUrl } = createTestApp(aiRouter);
async function call(method: string, path: string, who = A_OWNER, body?: unknown) {
  const res = await fetch(`${baseUrl()}${path}`, {
    method,
    headers: { "content-type": "application/json", "x-test-user": who },
    ...(body !== undefined ? { body: JSON.stringify(body) } : {}),
  });
  const text = await res.text();
  return { status: res.status, headers: res.headers, text, json: text && !text.startsWith(":") && !text.startsWith("event:") ? (JSON.parse(text) as any) : null };
}

function frames(text: string) {
  const out: Array<{ event: string; data: any }> = [];
  for (const block of text.split("\n\n")) {
    if (!block.trim() || block.startsWith(":")) continue;
    const ev = /^event: (.+)$/m.exec(block)?.[1];
    const data = /^data: (.+)$/m.exec(block)?.[1];
    if (ev && data) out.push({ event: ev, data: JSON.parse(data) });
  }
  return out;
}

let A: AskHousehold;
let B: AskHousehold;
const TO = daysAgo(0);
const FROM = daysAgo(20);

beforeAll(async () => {
  A = await seedAskHousehold("ra", { merchant: "ROUTEA" });
  B = await seedAskHousehold("rb", { merchant: "ROUTEB" });
  // Rebind the test users to the seeded households (their owner ids are generated by the seeder).
  HH[A_OWNER] = { householdId: A.householdId, ownerUserId: A.owner, actor: A.owner };
  HH[A_MEMBER] = { householdId: A.householdId, ownerUserId: A.owner, actor: A_MEMBER };
  HH[B_OWNER] = { householdId: B.householdId, ownerUserId: B.owner, actor: B.owner };
  HH[C_OWNER] = { ...(await createTestHousehold(C_OWNER)), ownerUserId: C_OWNER };
  HH[RL_OWNER] = { ...(await createTestHousehold(RL_OWNER)), ownerUserId: RL_OWNER };
});

async function chat(conversationId: string, text: string, who = A_OWNER, extra: Record<string, unknown> = {}) {
  return call("POST", "/ai/chat", who, { conversationId, text, ...extra });
}
const newConv = async (who = A_OWNER) => (await call("POST", "/ai/conversations", who)).json.id as string;

describe("conversations", () => {
  it("create, list and read are the signed-in person's own", async () => {
    resetFake();
    const id = await newConv();
    const list = await call("GET", "/ai/conversations?limit=5");
    expect(list.json.conversations.map((c: any) => c.id)).toContain(id);
    expect((await call("GET", `/ai/conversations/${id}`)).json.messages).toEqual([]);
    // another household, and another member of the same household: both 404
    expect((await call("GET", `/ai/conversations/${id}`, B_OWNER)).status).toBe(404);
    expect((await call("GET", `/ai/conversations/${id}`, A_MEMBER)).status).toBe(404);
    expect((await call("GET", "/ai/conversations", A_MEMBER)).json.conversations.map((c: any) => c.id)).not.toContain(id);
    expect((await chat(id, "hi", B_OWNER)).status).toBe(404);
    expect((await call("GET", "/ai/conversations/not-a-uuid")).status).toBe(404);
    expect((await call("GET", "/ai/conversations?limit=21")).status).toBe(400);
  });
});

describe("POST /ai/chat (server-sent events)", () => {
  it("streams frames the generated schema accepts, then the stored answer is readable", async () => {
    resetFake();
    queueFakeChat({
      calls: [{ name: "get_spending_summary", input: { from: FROM, to: TO } }],
      text: (r) => `You spent $${JSON.parse(r[0]!).spent.toFixed(2)}.`,
    });
    const id = await newConv();
    const r = await chat(id, "How much did we spend?");
    expect(r.status).toBe(200);
    expect(r.headers.get("content-type")).toContain("text/event-stream");
    expect(r.headers.get("cache-control")).toBe("no-cache, no-transform");
    expect(r.headers.get("x-accel-buffering")).toBe("no");
    const fs = frames(r.text);
    for (const f of fs) {
      expect(AiChatResponse.safeParse(f.data).success, JSON.stringify(f)).toBe(true);
      expect(f.data.type).toBe(f.event);
    }
    expect(fs.map((f) => f.event)).toContain("token");
    expect(fs.slice(0, 2).map((f) => [f.data.name, f.data.status])).toEqual([["get_spending_summary", "running"], ["get_spending_summary", "done"]]);
    const done = fs.at(-1)!;
    expect(done.event).toBe("done");
    expect(done.data).toMatchObject({ grounded: true, demo: true, text: "You spent $111.70." });
    // polling fallback
    const conv = (await call("GET", `/ai/conversations/${id}`)).json;
    expect(conv.conversation.title).toBe("How much did we spend?");
    expect(conv.messages.map((m: any) => m.role)).toEqual(["user", "tool", "assistant"]);
    expect(conv.messages[1].content).toEqual({ name: "get_spending_summary" }); // the result stays on the server
    expect(conv.messages[2].id).toBe(done.data.messageId);
  });

  it("sends a ping comment while the answer is slow", async () => {
    resetFake();
    queueFakeChat({ text: "slow one", delayMs: 200 });
    const r = await chat(await newConv(), "hi");
    expect(r.text).toContain(": ping");
    expect(frames(r.text).at(-1)!.event).toBe("done");
  });

  it("reports a failure as an error frame", async () => {
    resetFake();
    process.env.AI_ENABLED = "false";
    try {
      const r = await chat(await newConv(), "hi");
      const last = frames(r.text).at(-1)!;
      expect(AiChatResponse.safeParse(last.data).success).toBe(true);
      expect(last.data).toMatchObject({ type: "error", code: "disabled", retryable: false });
    } finally {
      process.env.AI_ENABLED = "true";
    }
  });

  it("validates the body and refuses a second question on a busy conversation", async () => {
    resetFake();
    const id = await newConv();
    expect((await chat(id, "")).status).toBe(400);
    expect((await chat(id, "x".repeat(2001))).status).toBe(400);
    expect((await call("POST", "/ai/chat", A_OWNER, { text: "no conversation" })).status).toBe(400);
    queueFakeChat({ text: "first", delayMs: 300 });
    const first = chat(id, "one");
    await new Promise((r) => setTimeout(r, 100));
    expect((await chat(id, "two")).status).toBe(409);
    expect(frames((await first).text).at(-1)!.event).toBe("done");
  });

  it("userAskedToChange comes only from the request flag: off proposes, on files", async () => {
    resetFake();
    const call1 = { name: "set_category", input: { txnId: A.txns.shell, categoryId: A.cats.Dining, reason: "fuel" } };
    queueFakeChat({ calls: [call1], text: "I suggested Dining." });
    await chat(await newConv(), "what is the shell charge?");
    let [t] = await db.select().from(transactionsTable).where(eq(transactionsTable.id, A.txns.shell));
    expect(t!.categoryId).toBeNull();
    expect((await call("GET", "/agent/proposals")).json.proposals.some((p: any) => p.kind === "set_category")).toBe(true);

    queueFakeChat({ calls: [call1], text: "Filed under Dining." });
    await chat(await newConv(), "file the shell charge under dining", A_OWNER, { userAskedToChange: true });
    [t] = await db.select().from(transactionsTable).where(eq(transactionsTable.id, A.txns.shell));
    expect(t!.categoryId).toBe(A.cats.Dining);
  });
});

describe("proposals", () => {
  const propose = async (h: AskHousehold, kind: string, target: string, after: number) => {
    const run = await newRun(h.householdId);
    const tools = makeTools({ householdId: h.householdId, ownerUserId: h.owner, actorUserId: h.owner, runId: run });
    const t = tools.find((x) => x.name === "propose_plan_change")!;
    const r = JSON.parse(await t.run({ kind, target, after, rationale: "because" }));
    expect(r.proposalId, JSON.stringify(r)).toBeTruthy();
    return r.proposalId as string;
  };
  const status = async (id: string) => (await db.select().from(agentProposalsTable).where(eq(agentProposalsTable.id, id)))[0]!;

  it("set_category: approve files it through the hand path and the action is undoable", async () => {
    const txn = A.txns.coffee;
    const run = await newRun(A.householdId);
    const tools = makeTools({ householdId: A.householdId, ownerUserId: A.owner, actorUserId: A.owner, runId: run });
    const pid = JSON.parse(await tools.find((t) => t.name === "set_category")!.run({ txnId: txn, categoryId: A.cats.Dining, reason: "r" })).proposalId;
    const open = await call("GET", "/agent/proposals");
    expect(open.json.proposals.find((p: any) => p.id === pid)).toMatchObject({ kind: "set_category", status: "proposed", runId: run });
    const ok = await call("POST", `/agent/proposals/${pid}/approve`, A_MEMBER);
    expect(ok.status).toBe(200);
    expect(ok.json).toMatchObject({ status: "applied", decidedBy: A_MEMBER });
    const [t] = await db.select().from(transactionsTable).where(eq(transactionsTable.id, txn));
    expect(t).toMatchObject({ categoryId: A.cats.Dining, categoryLockedByUser: true });
    const [act] = await db.select().from(agentActionsTable).where(eq(agentActionsTable.id, ok.json.appliedActionId));
    expect(act).toMatchObject({ type: "set_category", outcome: "applied", reversible: true, runId: run });
    expect((await undoDecision(A.householdId, (act!.after as any).decisionId)).status).toBe(200);
    expect((await call("POST", `/agent/proposals/${pid}/approve`)).status).toBe(409); // already decided
  });

  it("weekly_limit: only the owner applies it; a member's try leaves it open", async () => {
    const pid = await propose(A, "weekly_limit", "weekly", 150);
    const denied = await call("POST", `/agent/proposals/${pid}/approve`, A_MEMBER);
    expect(denied.status).toBe(403);
    expect((await status(pid)).status).toBe("proposed");
    const ok = await call("POST", `/agent/proposals/${pid}/approve`, A_OWNER);
    expect(ok.status).toBe(200);
    const [plan] = await db.select().from(allowancePlansTable).where(eq(allowancePlansTable.id, A.planId));
    expect(plan).toMatchObject({ amount: "150.00", source: "owner", createdByKind: "user" });
    const [act] = await db.select().from(agentActionsTable).where(eq(agentActionsTable.id, ok.json.appliedActionId));
    expect(act).toMatchObject({ type: "propose", outcome: "applied", targetKind: "weekly_limit", before: { amount: 200 }, after: { amount: 150 } });
  });

  it("budget_line, extra_debt_payment and bill_amount apply through their own writers", async () => {
    const line = await propose(A, "budget_line", A.expenseCatId, 80);
    const extra = await propose(A, "extra_debt_payment", "avalanche", 100);
    const bill = await propose(A, "bill_amount", A.billId, 55);
    for (const id of [line, extra, bill]) expect((await call("POST", `/agent/proposals/${id}/approve`)).status).toBe(200);
    const [l] = await db.select().from(budgetLinesTable).where(and(eq(budgetLinesTable.householdId, A.householdId), eq(budgetLinesTable.categoryId, A.expenseCatId)));
    expect(l).toMatchObject({ plannedAmount: "80.00" });
    expect(l!.monthStart).toBe(`${householdToday(new Date()).slice(0, 7)}-01`);
    const [s] = await db.select().from(avalancheSettingsTable).where(eq(avalancheSettingsTable.userId, A.owner));
    expect(s!.manualExtra).toBe("100.00");
    const [b] = await db.select().from(recurringItemsTable).where(eq(recurringItemsTable.id, A.billId));
    expect(b!.amount).toBe("55.00");
  });

  it("reject, double decisions, expiry and another household's id", async () => {
    const pid = await propose(A, "bill_amount", A.billId, 40);
    expect((await call("POST", `/agent/proposals/${pid}/approve`, B_OWNER)).status).toBe(404);
    expect((await call("POST", `/agent/proposals/${pid}/reject`, B_OWNER)).status).toBe(404);
    expect((await call("GET", "/agent/proposals?status=all", B_OWNER)).json.proposals.map((p: any) => p.id)).not.toContain(pid);
    const rej = await call("POST", `/agent/proposals/${pid}/reject`);
    expect(rej.json).toMatchObject({ status: "rejected", decidedBy: A.owner });
    expect((await call("POST", `/agent/proposals/${pid}/reject`)).status).toBe(409);
    expect((await call("POST", `/agent/proposals/${pid}/approve`)).status).toBe(409);
    const [b] = await db.select().from(recurringItemsTable).where(eq(recurringItemsTable.id, A.billId));
    expect(b!.amount).toBe("55.00"); // a rejection moves nothing

    const old = await propose(A, "bill_amount", A.billId, 41);
    await db.update(agentProposalsTable).set({ expiresAt: new Date(Date.now() - 1000) }).where(eq(agentProposalsTable.id, old));
    expect((await call("GET", "/agent/proposals")).json.proposals.map((p: any) => p.id)).not.toContain(old);
    expect((await call("GET", "/agent/proposals?status=expired")).json.proposals.map((p: any) => p.id)).toContain(old);
    const late = await call("POST", `/agent/proposals/${old}/approve`);
    expect(late.status).toBe(409);
    expect(late.json.error).toMatch(/expired/);
    expect((await call("POST", "/agent/proposals/nope/approve")).status).toBe(404);
  });

  it("two taps at once apply once", async () => {
    const pid = await propose(A, "bill_amount", A.billId, 52);
    const [x, y] = await Promise.all([call("POST", `/agent/proposals/${pid}/approve`), call("POST", `/agent/proposals/${pid}/approve`, A_MEMBER)]);
    expect([x.status, y.status].sort()).toEqual([200, 409]);
    const p = await status(pid);
    expect(p.status).toBe("applied");
    const acts = await db.select().from(agentActionsTable).where(and(eq(agentActionsTable.runId, p.runId), eq(agentActionsTable.targetKind, "bill_amount"), eq(agentActionsTable.outcome, "applied")));
    expect(acts).toHaveLength(1);
  });

  it("a target that vanished leaves the proposal open and changes nothing", async () => {
    const run = await newRun(A.householdId);
    const tools = makeTools({ householdId: A.householdId, ownerUserId: A.owner, actorUserId: A.owner, runId: run });
    const [gone] = await db.insert(transactionsTable).values({ userId: A.owner, householdId: A.householdId, occurredOn: daysAgo(1), description: "GONE", amount: "-3.00", source: "plaid:bank" }).returning({ id: transactionsTable.id });
    const pid = JSON.parse(await tools.find((t) => t.name === "set_category")!.run({ txnId: gone!.id, categoryId: A.cats.Dining, reason: "r" })).proposalId;
    await db.delete(transactionsTable).where(eq(transactionsTable.id, gone!.id));
    expect((await call("POST", `/agent/proposals/${pid}/approve`)).status).toBe(404);
    expect((await status(pid)).status).toBe("proposed");
  });
});

describe("memory", () => {
  it("CRUD, soft delete, member scope, and a person's word replaces an agent's note", async () => {
    const put = await call("PUT", "/memory/spending/Coffee%20is%20fine", A_OWNER, { value: "  Coffee is a treat  " });
    expect(put.status).toBe(200);
    expect(put.json).toMatchObject({ scope: "spending", key: "Coffee is fine", value: { text: "Coffee is a treat" }, source: "user_stated", createdByKind: "user", memberUserId: null });
    const again = await call("PUT", "/memory/spending/Coffee%20is%20fine", A_MEMBER, { value: "Coffee is fine" });
    expect(again.json.id).toBe(put.json.id);
    expect(again.json.value).toEqual({ text: "Coffee is fine" });
    const mine = await call("PUT", "/memory/general/My%20note", A_MEMBER, { value: "only me", mine: true });
    expect(mine.json.memberUserId).toBe(A_MEMBER);
    const asOwner = (await call("GET", "/memory", A_OWNER)).json.memories.map((m: any) => m.key);
    expect(asOwner).toContain("Coffee is fine");
    expect(asOwner).not.toContain("My note");
    expect((await call("GET", "/memory", A_MEMBER)).json.memories.map((m: any) => m.key)).toContain("My note");
    expect((await call("GET", "/memory", B_OWNER)).json.memories.map((m: any) => m.key)).not.toContain("Coffee is fine");

    await upsertAgentMemory(A.householdId, A.owner, { scope: "general", key: "agent note", value: { text: "from agent", kind: "preference" } });
    const over = await call("PUT", "/memory/general/agent%20note", A_OWNER, { value: "now a person's" });
    expect(over.json).toMatchObject({ source: "user_stated", createdByKind: "user" });

    expect((await call("DELETE", `/memory/${put.json.id}`, B_OWNER)).status).toBe(404);
    expect((await call("DELETE", `/memory/${put.json.id}`, A_MEMBER)).status).toBe(204);
    expect((await call("GET", "/memory")).json.memories.map((m: any) => m.id)).not.toContain(put.json.id);
    expect((await call("DELETE", `/memory/${put.json.id}`)).status).toBe(404);
    const [row] = await db.select().from(agentMemoryTable).where(eq(agentMemoryTable.id, put.json.id));
    expect(row!.revokedAt).not.toBeNull(); // kept for the trail
    const back = await call("PUT", "/memory/spending/Coffee%20is%20fine", A_OWNER, { value: "back" });
    expect(back.json.id).toBe(put.json.id);
    expect((await call("GET", "/memory")).json.memories.map((m: any) => m.id)).toContain(put.json.id);
  });

  it("validates scope, key and value", async () => {
    expect((await call("PUT", "/memory/nonsense/k", A_OWNER, { value: "v" })).status).toBe(400);
    expect((await call("PUT", "/memory/general/k", A_OWNER, { value: "" })).status).toBe(400);
    expect((await call("PUT", "/memory/general/k", A_OWNER, { value: "v".repeat(301) })).status).toBe(400);
    expect((await call("PUT", `/memory/general/${"k".repeat(61)}`, A_OWNER, { value: "v" })).status).toBe(400);
    expect((await call("PUT", "/memory/general/k", A_OWNER, { value: "v", extra: 1 })).status).toBe(400);
  });
});

describe("wish list", () => {
  it("starts a waiting period; a yes waits, a no never does", async () => {
    const today = householdToday(new Date());
    const add = await call("POST", "/wishlist", A_OWNER, { title: "  Bike  ", amount: 300 });
    expect(add.status).toBe(201);
    expect(add.json).toMatchObject({ title: "Bike", amount: 300, decision: "pending", waitingUntil: addDaysISO(today, 7), waitingDaysLeft: 7, requestedBy: A.owner });
    expect((await call("PATCH", `/wishlist/${add.json.id}`, A_MEMBER, { decision: "approved" })).status).toBe(409);
    expect((await call("PATCH", `/wishlist/${add.json.id}`, B_OWNER, { decision: "declined" })).status).toBe(404);
    const edit = await call("PATCH", `/wishlist/${add.json.id}`, A_OWNER, { title: "Road bike", amount: null });
    expect(edit.json).toMatchObject({ title: "Road bike", amount: null, decision: "pending" });
    const no = await call("PATCH", `/wishlist/${add.json.id}`, A_OWNER, { decision: "declined" });
    expect(no.json.decision).toBe("declined");
    expect(no.json.decidedAt).not.toBeNull();
    await db.update(wishlistItemsTable).set({ waitingUntil: addDaysISO(today, -1) }).where(eq(wishlistItemsTable.id, add.json.id));
    const yes = await call("PATCH", `/wishlist/${add.json.id}`, A_OWNER, { decision: "approved" });
    expect(yes.json).toMatchObject({ decision: "approved", waitingDaysLeft: 0 });
    const list = await call("GET", "/wishlist");
    expect(list.json.waitDays).toBe(7);
    expect(list.json.items.map((i: any) => i.id)).toContain(add.json.id);
    expect((await call("GET", "/wishlist", B_OWNER)).json.items.map((i: any) => i.id)).not.toContain(add.json.id);
    expect((await call("POST", "/wishlist", A_OWNER, { title: "x", categoryId: B.cats.Groceries })).status).toBe(400);
    expect((await call("POST", "/wishlist", A_OWNER, { title: "" })).status).toBe(400);
  });
});

describe("AI usage", () => {
  it("sums the month: cost by task, calls, failures, blocks and the cache-hit ratio", async () => {
    const hh = HH[C_OWNER]!.householdId;
    const lastMonth = new Date();
    lastMonth.setUTCMonth(lastMonth.getUTCMonth() - 1);
    await db.insert(aiUsageTable).values([
      { householdId: hh, task: "chat", model: "claude-opus-5-5", status: "ok", costUsd: "0.100000", inputTokens: 1000, cacheReadTokens: 3000, cacheWriteTokens: 0 },
      { householdId: hh, task: "chat", model: "claude-opus-5-5", status: "ok", costUsd: "0.050000", inputTokens: 500, cacheReadTokens: 500, cacheWriteTokens: 0 },
      { householdId: hh, task: "chat", model: "claude-opus-5-5", status: "api_error", costUsd: null },
      { householdId: hh, task: "chat", model: "claude-opus-5-5", status: "budget_exceeded", costUsd: "0" },
      { householdId: hh, task: "categorize", model: "claude-opus-5-5", status: "ok", costUsd: "0.020000", inputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 4000 },
      { householdId: hh, task: "chat", model: "claude-opus-5-5", status: "ok", costUsd: "9.000000", createdAt: lastMonth },
    ]);
    for (let i = 0; i < 22; i++) await newRun(hh);
    const s = (await call("GET", "/ai/usage/summary", C_OWNER)).json;
    expect(s.monthToDateUsd).toBeCloseTo(0.17, 6);
    expect(s).toMatchObject({ calls: 4, failures: 1, blocked: 1 });
    expect(s.cacheHitRatio).toBeCloseTo(3500 / (1500 + 3500 + 4000), 4);
    expect(s.byTask).toEqual([
      { task: "categorize", costUsd: 0.02, calls: 1, failures: 0 },
      { task: "chat", costUsd: 0.15, calls: 3, failures: 1 },
    ]);
    expect(s.budget).toMatchObject({ monthlyCapUsd: 25, hardCapUsd: 40, pausedUntil: null });
    expect(s.budget.dailyCaps.chat).toBe(40);
    expect(s.recentRuns).toHaveLength(20);
    expect(Object.keys(s.recentRuns[0]).sort()).toEqual(["costUsd", "finishedAt", "id", "inputTokens", "kind", "outputTokens", "startedAt", "status", "summary", "trigger"]);
    expect((await call("GET", "/ai/usage/summary", B_OWNER)).json.monthToDateUsd).toBe(0);
  });

  it("PUT /ai/budget is the owner's, validates, and a pause blocks the next question", async () => {
    expect((await call("PUT", "/ai/budget", A_MEMBER, { monthlyCapUsd: 30 })).status).toBe(403);
    expect((await call("PUT", "/ai/budget", A_OWNER, { monthlyCapUsd: 60, hardCapUsd: 50 })).status).toBe(400);
    expect((await call("PUT", "/ai/budget", A_OWNER, { monthlyCapUsd: -1 })).status).toBe(400);
    expect((await call("PUT", "/ai/budget", A_OWNER, { surprise: 1 })).status).toBe(400);
    const ok = await call("PUT", "/ai/budget", A_OWNER, { monthlyCapUsd: 30, hardCapUsd: 50 });
    expect(ok.json).toMatchObject({ monthlyCapUsd: 30, hardCapUsd: 50, pausedUntil: null });
    const until = new Date(Date.now() + 3_600_000).toISOString();
    const paused = await call("PUT", "/ai/budget", A_OWNER, { pausedUntil: until });
    expect(paused.json).toMatchObject({ monthlyCapUsd: 30, pausedUntil: until });
    resetFake();
    const r = await chat(await newConv(), "hi");
    expect(frames(r.text).at(-1)!.data).toMatchObject({ type: "error", code: "budget_exceeded" });
    expect((await call("PUT", "/ai/budget", A_OWNER, { pausedUntil: null })).json.pausedUntil).toBeNull();
    await db.delete(aiBudgetTable).where(eq(aiBudgetTable.householdId, A.householdId));
  });
});

describe("rate limit", () => {
  it("is 30 a minute per signed-in person, on /ai/* only", async () => {
    for (let i = 0; i < 30; i++) expect((await call("GET", "/ai/conversations", RL_OWNER)).status).toBe(200);
    expect((await call("GET", "/ai/conversations", RL_OWNER)).status).toBe(429);
    expect((await call("GET", "/ai/conversations", B_OWNER)).status).toBe(200); // someone else is not affected
    expect((await call("GET", "/memory", RL_OWNER)).status).toBe(200); // not an /ai route
  });
});

void agentMessagesTable;
