import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import transactionsRouter from "./transactions";
import debtsRouter from "./debts";
import recurringRouter from "./recurring";
import budgetRouter from "./budget";
import mappingRouter from "./mapping";
import settingsRouter from "./settings";
import importRouter from "./import";
import forecastRouter from "./forecast";
import dashboardBudgetsRouter from "./dashboardBudgets";
import weeklySettlementsRouter from "./weeklySettlements";
import avalancheRouter from "./avalanche";
import plaidRouter from "./plaid";
import billsRouter from "./bills";
import meRouter from "./me";
import invitationsRouter from "./invitations";
import membersRouter from "./members";
import amexRouter from "./amex";
import advisorRouter from "./advisor";
import advisorUndoRouter from "./advisorUndo";
import advisorProposalsRouter from "./advisorProposals";
import weeklyDebriefRouter from "./weeklyDebrief";
import reportsRouter from "./reports";
import bankingRouter from "./banking";
import billsInsightsRouter from "./billsInsights";

const router: IRouter = Router();

router.use(healthRouter);
router.use(dashboardRouter);
router.use(transactionsRouter);
router.use(debtsRouter);
router.use(recurringRouter);
router.use(budgetRouter);
router.use(mappingRouter);
router.use(settingsRouter);
router.use(importRouter);
router.use(forecastRouter);
router.use(dashboardBudgetsRouter);
router.use(weeklySettlementsRouter);
router.use(avalancheRouter);
router.use(plaidRouter);
router.use(billsRouter);
router.use(meRouter);
router.use(invitationsRouter);
router.use(membersRouter);
router.use(amexRouter);
router.use(advisorRouter);
router.use(advisorUndoRouter);
router.use(advisorProposalsRouter);
router.use(weeklyDebriefRouter);
router.use(reportsRouter);
router.use(bankingRouter);
router.use(billsInsightsRouter);

export default router;
