// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/budget-design-system/FintechMinimal.tsx": () => import("../components/mockups/budget-design-system/FintechMinimal.tsx"),
  "./components/mockups/budget-design-system/SlateProfessional.tsx": () => import("../components/mockups/budget-design-system/SlateProfessional.tsx"),
  "./components/mockups/budget-design-system/WarmBanking.tsx": () => import("../components/mockups/budget-design-system/WarmBanking.tsx"),
  "./components/mockups/h2-redesign/EditorialWarm.tsx": () => import("../components/mockups/h2-redesign/EditorialWarm.tsx"),
  "./components/mockups/h2-redesign/FintechDark.tsx": () => import("../components/mockups/h2-redesign/FintechDark.tsx"),
  "./components/mockups/h2-redesign/GraphiteVault.tsx": () => import("../components/mockups/h2-redesign/GraphiteVault.tsx"),
  "./components/mockups/h2-redesign/ObsidianGlass.tsx": () => import("../components/mockups/h2-redesign/ObsidianGlass.tsx"),
  "./components/mockups/h2-redesign/QuietBank.tsx": () => import("../components/mockups/h2-redesign/QuietBank.tsx"),
  "./components/mockups/h2-redesign/SteelAtelier.tsx": () => import("../components/mockups/h2-redesign/SteelAtelier.tsx")
};
